### ISSUE TITLE
Is contains on array (maybe also on string) not supported?

### ISSUE THREAD

**Issue by jeroenmeulendijks** [skyhookadventure/appsync-template-tester#17]
According to https://stackoverflow.com/questions/57604233/how-to-check-if-value-exists-in-an-array-using-velocity-template-language you can check in VTL if an array contains a certain key. I checked this by using the following VTL in AWS AppSync and it works. But when I try to unittest it with this library, it fails. It seems that 'contains' is not recognized and completely ignored.

I minimized the VTL to the part that doesn't work, so it's not the complete VTL I'm using but I think this should be enough
VTL:
```
#foreach($item in $abilities)
  #if($item.array.contains($ctx.args.ability))
    ...
  #end
#end
```
Where $item.array is an actual array like: ['1', '2'] and $ctx.args.ability is a string like '2'.

Could you help me understand the issue here?

**Comment by jeroenmeulendijks** [comment]
Created a PR for this one: https://github.com/skyhookadventure/appsync-template-tester/pull/18

**Comment by alan-cooney** [comment]
Hi @jeroenmeulendijks - thanks for submitting this PR.

Have you considered adding it in https://github.com/shepherdwind/velocity.js instead - as this is quite a lot of code compared to adding a few lines in https://github.com/shepherdwind/velocity.js/blob/master/src/compile/methods.js . Other array methods are supported (e.g. `.size()`, so it looks like you just need to add `.contains()`.

**Comment by jeroenmeulendijks** [comment]
Hi @alan-cooney,

Thanks for your reply.

No I didn't consider that, mainly (and I guess it's a bad reason) because the code in this merge request is highly inspired by https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-appsync-simulator/src/velocity/value-mapper so I assumed that they implemented it themselves because it fell outside the scope of velocity.js (as they use this library as well)

In our fork I implemented this behavior so I'm fine with you rejecting/closing the MR if you think this should be handled by velocity.js. I will create a issue on that repository, but not sure if I will be able to create a MR as the structure is different I need to invest some time to create the correct code.

**Comment by alan-cooney** [comment]
Makes sense - I'll close for now. I think it's just 2-3 lines of code to change in velocity.js (in that `methods.js` file) so it's probably better placed there .
