### ISSUE TITLE
Feature: $ctx.stash checks

### ISSUE THREAD

**Issue by ssssota** [skyhookadventure/appsync-template-tester#9]
### Background

$ctx.stash can keep data across mapping templates in Pipline resolver.

> What this means is you can use the stash to pass arbitrary data across request and response mapping templates, and across functions in a pipeline resolver.

https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html#ctx-stash

### Suggestion

We want to check stash values after resolve.

Like this:

```typescript
const vtl = '$ctx.stash.put("key", "value")';
const parser = new Parser(vtl);
const res = parser.resolve({});
expect(parser.stash).toStrictEqual({ key: "value" });
```

**Comment by alan-cooney** [comment]
Agreed this sounds useful - please do feel free to add a PR if you have time.
